# Generated by Django 3.0.8 on 2020-07-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('pitch', models.CharField(default='', max_length=300)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('votes', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea')),
            ],
        ),
    ]
