# Generated by Django 3.0.8 on 2020-07-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20200729_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['creation_date']},
        ),
    ]
