# Generated by Django 3.0.8 on 2020-07-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20200729_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea'),
        ),
    ]
