# Generated by Django 3.0.8 on 2020-07-29 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20200729_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
